# Generated by Django 2.0.4 on 2018-04-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0002_remove_environment_high_score'),
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_path', models.CharField(max_length=255)),
                ('high_score', models.FloatField()),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_runs', to='environments.Environment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount')),
            ],
        ),
    ]
