# Generated by Django 2.0.4 on 2018-04-30 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationrun',
            options={'verbose_name': 'Evaluation Run'},
        ),
    ]
