# Generated by Django 2.0.4 on 2018-04-30 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboards', '0002_auto_20180430_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationrun',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
