# Generated by Django 2.0.4 on 2018-04-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environment',
            name='high_score',
        ),
    ]
