# Generated by Django 2.0.4 on 2018-05-19 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='test-token', max_length=255)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='openrl_token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
